// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "prim_assert.sv"

module pwm_reg_top
  import pwm_reg_pkg::* ;
(
  input logic clk_i,
  input logic rst_ni,
  // From TLUL
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output pwm_reg_pkg::pwm_reg2hw_t reg2hw, // Write

  // Devmode
  input logic devmode_i // If 1, explicit error return for unmapped register access
);

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(0),
    .EnableDataIntgGen(0)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;


  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic regwen_we;
  logic regwen_qs;
  logic regwen_wd;
  logic cfg_we;
  logic [31:0] cfg_qs;
  logic cfg_busy;
  logic pwm_en_we;
  logic [1:0] pwm_en_qs;
  logic pwm_en_busy;
  logic invert_we;
  logic [1:0] invert_qs;
  logic invert_busy;
  logic pwm_param_0_we;
  logic [31:0] pwm_param_0_qs;
  logic pwm_param_0_busy;
  logic pwm_param_1_we;
  logic [31:0] pwm_param_1_qs;
  logic pwm_param_1_busy;
  logic duty_cycle_0_we;
  logic [31:0] duty_cycle_0_qs;
  logic duty_cycle_0_busy;
  logic duty_cycle_1_we;
  logic [31:0] duty_cycle_1_qs;
  logic duty_cycle_1_busy;
  logic blink_param_0_we;
  logic [31:0] blink_param_0_qs;
  logic blink_param_0_busy;
  logic blink_param_1_we;
  logic [31:0] blink_param_1_qs;
  logic blink_param_1_busy;
  // Define register CDC handling.
  // CDC handling is done on a per-reg instead of per-field boundary.

  logic [26:0]  _cfg_clk_div_qs_int;
  logic [3:0]  _cfg_dc_resn_qs_int;
  logic  _cfg_cntr_en_qs_int;
  logic [31:0] _cfg_qs;
  logic [31:0] _cfg_wdata;
  logic _cfg_we;
  logic unused__cfg_wdata;
  logic _cfg_regwen;

  always_comb begin
    _cfg_qs = 32'h38008000;
    _cfg_qs[26:0] = _cfg_clk_div_qs_int;
    _cfg_qs[30:27] = _cfg_dc_resn_qs_int;
    _cfg_qs[31] = _cfg_cntr_en_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h38008000),
    .BitMask(32'hffffffff),
    .DstWrReq(0)
  ) u_cfg_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (cfg_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (cfg_busy),
    .src_qs_o     (cfg_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_cfg_qs),
    .dst_we_o     (_cfg_we),
    .dst_re_o     (),
    .dst_regwen_o (_cfg_regwen),
    .dst_wd_o     (_cfg_wdata)
  );
  assign unused__cfg_wdata =
      ^_cfg_wdata;

  logic  _pwm_en_en_0_qs_int;
  logic  _pwm_en_en_1_qs_int;
  logic [1:0] _pwm_en_qs;
  logic [1:0] _pwm_en_wdata;
  logic _pwm_en_we;
  logic unused__pwm_en_wdata;
  logic _pwm_en_regwen;

  always_comb begin
    _pwm_en_qs = 2'h0;
    _pwm_en_qs[0] = _pwm_en_en_0_qs_int;
    _pwm_en_qs[1] = _pwm_en_en_1_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(2),
    .ResetVal(2'h0),
    .BitMask(2'h3),
    .DstWrReq(0)
  ) u_pwm_en_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (pwm_en_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[1:0]),
    .src_busy_o   (pwm_en_busy),
    .src_qs_o     (pwm_en_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_pwm_en_qs),
    .dst_we_o     (_pwm_en_we),
    .dst_re_o     (),
    .dst_regwen_o (_pwm_en_regwen),
    .dst_wd_o     (_pwm_en_wdata)
  );
  assign unused__pwm_en_wdata =
      ^_pwm_en_wdata;

  logic  _invert_invert_0_qs_int;
  logic  _invert_invert_1_qs_int;
  logic [1:0] _invert_qs;
  logic [1:0] _invert_wdata;
  logic _invert_we;
  logic unused__invert_wdata;
  logic _invert_regwen;

  always_comb begin
    _invert_qs = 2'h0;
    _invert_qs[0] = _invert_invert_0_qs_int;
    _invert_qs[1] = _invert_invert_1_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(2),
    .ResetVal(2'h0),
    .BitMask(2'h3),
    .DstWrReq(0)
  ) u_invert_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (invert_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[1:0]),
    .src_busy_o   (invert_busy),
    .src_qs_o     (invert_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_invert_qs),
    .dst_we_o     (_invert_we),
    .dst_re_o     (),
    .dst_regwen_o (_invert_regwen),
    .dst_wd_o     (_invert_wdata)
  );
  assign unused__invert_wdata =
      ^_invert_wdata;

  logic [15:0]  _pwm_param_0_phase_delay_0_qs_int;
  logic  _pwm_param_0_htbt_en_0_qs_int;
  logic  _pwm_param_0_blink_en_0_qs_int;
  logic [31:0] _pwm_param_0_qs;
  logic [31:0] _pwm_param_0_wdata;
  logic _pwm_param_0_we;
  logic unused__pwm_param_0_wdata;
  logic _pwm_param_0_regwen;

  always_comb begin
    _pwm_param_0_qs = 32'h0;
    _pwm_param_0_qs[15:0] = _pwm_param_0_phase_delay_0_qs_int;
    _pwm_param_0_qs[30] = _pwm_param_0_htbt_en_0_qs_int;
    _pwm_param_0_qs[31] = _pwm_param_0_blink_en_0_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h0),
    .BitMask(32'hc000ffff),
    .DstWrReq(0)
  ) u_pwm_param_0_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (pwm_param_0_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (pwm_param_0_busy),
    .src_qs_o     (pwm_param_0_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_pwm_param_0_qs),
    .dst_we_o     (_pwm_param_0_we),
    .dst_re_o     (),
    .dst_regwen_o (_pwm_param_0_regwen),
    .dst_wd_o     (_pwm_param_0_wdata)
  );
  assign unused__pwm_param_0_wdata =
      ^_pwm_param_0_wdata;

  logic [15:0]  _pwm_param_1_phase_delay_1_qs_int;
  logic  _pwm_param_1_htbt_en_1_qs_int;
  logic  _pwm_param_1_blink_en_1_qs_int;
  logic [31:0] _pwm_param_1_qs;
  logic [31:0] _pwm_param_1_wdata;
  logic _pwm_param_1_we;
  logic unused__pwm_param_1_wdata;
  logic _pwm_param_1_regwen;

  always_comb begin
    _pwm_param_1_qs = 32'h0;
    _pwm_param_1_qs[15:0] = _pwm_param_1_phase_delay_1_qs_int;
    _pwm_param_1_qs[30] = _pwm_param_1_htbt_en_1_qs_int;
    _pwm_param_1_qs[31] = _pwm_param_1_blink_en_1_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h0),
    .BitMask(32'hc000ffff),
    .DstWrReq(0)
  ) u_pwm_param_1_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (pwm_param_1_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (pwm_param_1_busy),
    .src_qs_o     (pwm_param_1_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_pwm_param_1_qs),
    .dst_we_o     (_pwm_param_1_we),
    .dst_re_o     (),
    .dst_regwen_o (_pwm_param_1_regwen),
    .dst_wd_o     (_pwm_param_1_wdata)
  );
  assign unused__pwm_param_1_wdata =
      ^_pwm_param_1_wdata;

  logic [15:0]  _duty_cycle_0_a_0_qs_int;
  logic [15:0]  _duty_cycle_0_b_0_qs_int;
  logic [31:0] _duty_cycle_0_qs;
  logic [31:0] _duty_cycle_0_wdata;
  logic _duty_cycle_0_we;
  logic unused__duty_cycle_0_wdata;
  logic _duty_cycle_0_regwen;

  always_comb begin
    _duty_cycle_0_qs = 32'h7fff7fff;
    _duty_cycle_0_qs[15:0] = _duty_cycle_0_a_0_qs_int;
    _duty_cycle_0_qs[31:16] = _duty_cycle_0_b_0_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h7fff7fff),
    .BitMask(32'hffffffff),
    .DstWrReq(0)
  ) u_duty_cycle_0_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (duty_cycle_0_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (duty_cycle_0_busy),
    .src_qs_o     (duty_cycle_0_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_duty_cycle_0_qs),
    .dst_we_o     (_duty_cycle_0_we),
    .dst_re_o     (),
    .dst_regwen_o (_duty_cycle_0_regwen),
    .dst_wd_o     (_duty_cycle_0_wdata)
  );
  assign unused__duty_cycle_0_wdata =
      ^_duty_cycle_0_wdata;

  logic [15:0]  _duty_cycle_1_a_1_qs_int;
  logic [15:0]  _duty_cycle_1_b_1_qs_int;
  logic [31:0] _duty_cycle_1_qs;
  logic [31:0] _duty_cycle_1_wdata;
  logic _duty_cycle_1_we;
  logic unused__duty_cycle_1_wdata;
  logic _duty_cycle_1_regwen;

  always_comb begin
    _duty_cycle_1_qs = 32'h7fff7fff;
    _duty_cycle_1_qs[15:0] = _duty_cycle_1_a_1_qs_int;
    _duty_cycle_1_qs[31:16] = _duty_cycle_1_b_1_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h7fff7fff),
    .BitMask(32'hffffffff),
    .DstWrReq(0)
  ) u_duty_cycle_1_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (duty_cycle_1_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (duty_cycle_1_busy),
    .src_qs_o     (duty_cycle_1_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_duty_cycle_1_qs),
    .dst_we_o     (_duty_cycle_1_we),
    .dst_re_o     (),
    .dst_regwen_o (_duty_cycle_1_regwen),
    .dst_wd_o     (_duty_cycle_1_wdata)
  );
  assign unused__duty_cycle_1_wdata =
      ^_duty_cycle_1_wdata;

  logic [15:0]  _blink_param_0_x_0_qs_int;
  logic [15:0]  _blink_param_0_y_0_qs_int;
  logic [31:0] _blink_param_0_qs;
  logic [31:0] _blink_param_0_wdata;
  logic _blink_param_0_we;
  logic unused__blink_param_0_wdata;
  logic _blink_param_0_regwen;

  always_comb begin
    _blink_param_0_qs = 32'h0;
    _blink_param_0_qs[15:0] = _blink_param_0_x_0_qs_int;
    _blink_param_0_qs[31:16] = _blink_param_0_y_0_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h0),
    .BitMask(32'hffffffff),
    .DstWrReq(0)
  ) u_blink_param_0_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (blink_param_0_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (blink_param_0_busy),
    .src_qs_o     (blink_param_0_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_blink_param_0_qs),
    .dst_we_o     (_blink_param_0_we),
    .dst_re_o     (),
    .dst_regwen_o (_blink_param_0_regwen),
    .dst_wd_o     (_blink_param_0_wdata)
  );
  assign unused__blink_param_0_wdata =
      ^_blink_param_0_wdata;

  logic [15:0]  _blink_param_1_x_1_qs_int;
  logic [15:0]  _blink_param_1_y_1_qs_int;
  logic [31:0] _blink_param_1_qs;
  logic [31:0] _blink_param_1_wdata;
  logic _blink_param_1_we;
  logic unused__blink_param_1_wdata;
  logic _blink_param_1_regwen;

  always_comb begin
    _blink_param_1_qs = 32'h0;
    _blink_param_1_qs[15:0] = _blink_param_1_x_1_qs_int;
    _blink_param_1_qs[31:16] = _blink_param_1_y_1_qs_int;
  end

  prim_reg_cdc #(
    .DataWidth(32),
    .ResetVal(32'h0),
    .BitMask(32'hffffffff),
    .DstWrReq(0)
  ) u_blink_param_1_cdc (
    .clk_src_i    (clk_i),
    .rst_src_ni   (rst_ni),
    .clk_dst_i    (clk_i),
    .rst_dst_ni   (rst_ni),
    .src_regwen_i (regwen_qs),
    .src_we_i     (blink_param_1_we),
    .src_re_i     ('0),
    .src_wd_i     (reg_wdata[31:0]),
    .src_busy_o   (blink_param_1_busy),
    .src_qs_o     (blink_param_1_qs), // for software read back
    .dst_update_i ('0),
    .dst_ds_i     ('0),
    .dst_qs_i     (_blink_param_1_qs),
    .dst_we_o     (_blink_param_1_we),
    .dst_re_o     (),
    .dst_regwen_o (_blink_param_1_regwen),
    .dst_wd_o     (_blink_param_1_wdata)
  );
  assign unused__blink_param_1_wdata =
      ^_blink_param_1_wdata;

  // Register instances
  // R[regwen]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessW0C),
    .RESVAL  (1'h1),
    .Mubi    (1'b0)
  ) u_regwen (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (regwen_we),
    .wd     (regwen_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (regwen_qs)
  );


  // R[cfg]: V(False)
  logic cfg_qe;
  logic [2:0] cfg_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_cfg0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&cfg_flds_we),
    .q_o(cfg_qe)
  );
  // Create REGWEN-gated WE signal
  logic _cfg_gated_we;
  assign _cfg_gated_we = _cfg_we & _cfg_regwen;
  //   F[clk_div]: 26:0
  prim_subreg #(
    .DW      (27),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (27'h8000),
    .Mubi    (1'b0)
  ) u_cfg_clk_div (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_cfg_gated_we),
    .wd     (_cfg_wdata[26:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (cfg_flds_we[0]),
    .q      (reg2hw.cfg.clk_div.q),
    .ds     (),

    // to register interface (read)
    .qs     (_cfg_clk_div_qs_int)
  );
  assign reg2hw.cfg.clk_div.qe = cfg_qe;

  //   F[dc_resn]: 30:27
  prim_subreg #(
    .DW      (4),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (4'h7),
    .Mubi    (1'b0)
  ) u_cfg_dc_resn (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_cfg_gated_we),
    .wd     (_cfg_wdata[30:27]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (cfg_flds_we[1]),
    .q      (reg2hw.cfg.dc_resn.q),
    .ds     (),

    // to register interface (read)
    .qs     (_cfg_dc_resn_qs_int)
  );
  assign reg2hw.cfg.dc_resn.qe = cfg_qe;

  //   F[cntr_en]: 31:31
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_cfg_cntr_en (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_cfg_gated_we),
    .wd     (_cfg_wdata[31]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (cfg_flds_we[2]),
    .q      (reg2hw.cfg.cntr_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (_cfg_cntr_en_qs_int)
  );
  assign reg2hw.cfg.cntr_en.qe = cfg_qe;


  // Subregister 0 of Multireg pwm_en
  // R[pwm_en]: V(False)
  logic pwm_en_qe;
  logic [1:0] pwm_en_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_pwm_en0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&pwm_en_flds_we),
    .q_o(pwm_en_qe)
  );
  // Create REGWEN-gated WE signal
  logic _pwm_en_gated_we;
  assign _pwm_en_gated_we = _pwm_en_we & _pwm_en_regwen;
  //   F[en_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_pwm_en_en_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_en_gated_we),
    .wd     (_pwm_en_wdata[0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_en_flds_we[0]),
    .q      (reg2hw.pwm_en[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_en_en_0_qs_int)
  );
  assign reg2hw.pwm_en[0].qe = pwm_en_qe;

  //   F[en_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_pwm_en_en_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_en_gated_we),
    .wd     (_pwm_en_wdata[1]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_en_flds_we[1]),
    .q      (reg2hw.pwm_en[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_en_en_1_qs_int)
  );
  assign reg2hw.pwm_en[1].qe = pwm_en_qe;


  // Subregister 0 of Multireg invert
  // R[invert]: V(False)
  logic invert_qe;
  logic [1:0] invert_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_invert0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&invert_flds_we),
    .q_o(invert_qe)
  );
  // Create REGWEN-gated WE signal
  logic _invert_gated_we;
  assign _invert_gated_we = _invert_we & _invert_regwen;
  //   F[invert_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_invert_invert_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_invert_gated_we),
    .wd     (_invert_wdata[0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (invert_flds_we[0]),
    .q      (reg2hw.invert[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (_invert_invert_0_qs_int)
  );
  assign reg2hw.invert[0].qe = invert_qe;

  //   F[invert_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_invert_invert_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_invert_gated_we),
    .wd     (_invert_wdata[1]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (invert_flds_we[1]),
    .q      (reg2hw.invert[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (_invert_invert_1_qs_int)
  );
  assign reg2hw.invert[1].qe = invert_qe;


  // Subregister 0 of Multireg pwm_param
  // R[pwm_param_0]: V(False)
  logic pwm_param_0_qe;
  logic [2:0] pwm_param_0_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_pwm_param0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&pwm_param_0_flds_we),
    .q_o(pwm_param_0_qe)
  );
  // Create REGWEN-gated WE signal
  logic _pwm_param_0_gated_we;
  assign _pwm_param_0_gated_we = _pwm_param_0_we & _pwm_param_0_regwen;
  //   F[phase_delay_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_pwm_param_0_phase_delay_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_param_0_gated_we),
    .wd     (_pwm_param_0_wdata[15:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_param_0_flds_we[0]),
    .q      (reg2hw.pwm_param[0].phase_delay.q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_param_0_phase_delay_0_qs_int)
  );
  assign reg2hw.pwm_param[0].phase_delay.qe = pwm_param_0_qe;

  //   F[htbt_en_0]: 30:30
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_pwm_param_0_htbt_en_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_param_0_gated_we),
    .wd     (_pwm_param_0_wdata[30]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_param_0_flds_we[1]),
    .q      (reg2hw.pwm_param[0].htbt_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_param_0_htbt_en_0_qs_int)
  );
  assign reg2hw.pwm_param[0].htbt_en.qe = pwm_param_0_qe;

  //   F[blink_en_0]: 31:31
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_pwm_param_0_blink_en_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_param_0_gated_we),
    .wd     (_pwm_param_0_wdata[31]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_param_0_flds_we[2]),
    .q      (reg2hw.pwm_param[0].blink_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_param_0_blink_en_0_qs_int)
  );
  assign reg2hw.pwm_param[0].blink_en.qe = pwm_param_0_qe;


  // Subregister 1 of Multireg pwm_param
  // R[pwm_param_1]: V(False)
  logic pwm_param_1_qe;
  logic [2:0] pwm_param_1_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_pwm_param1_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&pwm_param_1_flds_we),
    .q_o(pwm_param_1_qe)
  );
  // Create REGWEN-gated WE signal
  logic _pwm_param_1_gated_we;
  assign _pwm_param_1_gated_we = _pwm_param_1_we & _pwm_param_1_regwen;
  //   F[phase_delay_1]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_pwm_param_1_phase_delay_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_param_1_gated_we),
    .wd     (_pwm_param_1_wdata[15:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_param_1_flds_we[0]),
    .q      (reg2hw.pwm_param[1].phase_delay.q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_param_1_phase_delay_1_qs_int)
  );
  assign reg2hw.pwm_param[1].phase_delay.qe = pwm_param_1_qe;

  //   F[htbt_en_1]: 30:30
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_pwm_param_1_htbt_en_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_param_1_gated_we),
    .wd     (_pwm_param_1_wdata[30]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_param_1_flds_we[1]),
    .q      (reg2hw.pwm_param[1].htbt_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_param_1_htbt_en_1_qs_int)
  );
  assign reg2hw.pwm_param[1].htbt_en.qe = pwm_param_1_qe;

  //   F[blink_en_1]: 31:31
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_pwm_param_1_blink_en_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_pwm_param_1_gated_we),
    .wd     (_pwm_param_1_wdata[31]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (pwm_param_1_flds_we[2]),
    .q      (reg2hw.pwm_param[1].blink_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (_pwm_param_1_blink_en_1_qs_int)
  );
  assign reg2hw.pwm_param[1].blink_en.qe = pwm_param_1_qe;


  // Subregister 0 of Multireg duty_cycle
  // R[duty_cycle_0]: V(False)
  logic duty_cycle_0_qe;
  logic [1:0] duty_cycle_0_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_duty_cycle0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&duty_cycle_0_flds_we),
    .q_o(duty_cycle_0_qe)
  );
  // Create REGWEN-gated WE signal
  logic _duty_cycle_0_gated_we;
  assign _duty_cycle_0_gated_we = _duty_cycle_0_we & _duty_cycle_0_regwen;
  //   F[a_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h7fff),
    .Mubi    (1'b0)
  ) u_duty_cycle_0_a_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_duty_cycle_0_gated_we),
    .wd     (_duty_cycle_0_wdata[15:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (duty_cycle_0_flds_we[0]),
    .q      (reg2hw.duty_cycle[0].a.q),
    .ds     (),

    // to register interface (read)
    .qs     (_duty_cycle_0_a_0_qs_int)
  );
  assign reg2hw.duty_cycle[0].a.qe = duty_cycle_0_qe;

  //   F[b_0]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h7fff),
    .Mubi    (1'b0)
  ) u_duty_cycle_0_b_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_duty_cycle_0_gated_we),
    .wd     (_duty_cycle_0_wdata[31:16]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (duty_cycle_0_flds_we[1]),
    .q      (reg2hw.duty_cycle[0].b.q),
    .ds     (),

    // to register interface (read)
    .qs     (_duty_cycle_0_b_0_qs_int)
  );
  assign reg2hw.duty_cycle[0].b.qe = duty_cycle_0_qe;


  // Subregister 1 of Multireg duty_cycle
  // R[duty_cycle_1]: V(False)
  logic duty_cycle_1_qe;
  logic [1:0] duty_cycle_1_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_duty_cycle1_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&duty_cycle_1_flds_we),
    .q_o(duty_cycle_1_qe)
  );
  // Create REGWEN-gated WE signal
  logic _duty_cycle_1_gated_we;
  assign _duty_cycle_1_gated_we = _duty_cycle_1_we & _duty_cycle_1_regwen;
  //   F[a_1]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h7fff),
    .Mubi    (1'b0)
  ) u_duty_cycle_1_a_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_duty_cycle_1_gated_we),
    .wd     (_duty_cycle_1_wdata[15:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (duty_cycle_1_flds_we[0]),
    .q      (reg2hw.duty_cycle[1].a.q),
    .ds     (),

    // to register interface (read)
    .qs     (_duty_cycle_1_a_1_qs_int)
  );
  assign reg2hw.duty_cycle[1].a.qe = duty_cycle_1_qe;

  //   F[b_1]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h7fff),
    .Mubi    (1'b0)
  ) u_duty_cycle_1_b_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_duty_cycle_1_gated_we),
    .wd     (_duty_cycle_1_wdata[31:16]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (duty_cycle_1_flds_we[1]),
    .q      (reg2hw.duty_cycle[1].b.q),
    .ds     (),

    // to register interface (read)
    .qs     (_duty_cycle_1_b_1_qs_int)
  );
  assign reg2hw.duty_cycle[1].b.qe = duty_cycle_1_qe;


  // Subregister 0 of Multireg blink_param
  // R[blink_param_0]: V(False)
  logic blink_param_0_qe;
  logic [1:0] blink_param_0_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_blink_param0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&blink_param_0_flds_we),
    .q_o(blink_param_0_qe)
  );
  // Create REGWEN-gated WE signal
  logic _blink_param_0_gated_we;
  assign _blink_param_0_gated_we = _blink_param_0_we & _blink_param_0_regwen;
  //   F[x_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_blink_param_0_x_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_blink_param_0_gated_we),
    .wd     (_blink_param_0_wdata[15:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (blink_param_0_flds_we[0]),
    .q      (reg2hw.blink_param[0].x.q),
    .ds     (),

    // to register interface (read)
    .qs     (_blink_param_0_x_0_qs_int)
  );
  assign reg2hw.blink_param[0].x.qe = blink_param_0_qe;

  //   F[y_0]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_blink_param_0_y_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_blink_param_0_gated_we),
    .wd     (_blink_param_0_wdata[31:16]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (blink_param_0_flds_we[1]),
    .q      (reg2hw.blink_param[0].y.q),
    .ds     (),

    // to register interface (read)
    .qs     (_blink_param_0_y_0_qs_int)
  );
  assign reg2hw.blink_param[0].y.qe = blink_param_0_qe;


  // Subregister 1 of Multireg blink_param
  // R[blink_param_1]: V(False)
  logic blink_param_1_qe;
  logic [1:0] blink_param_1_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_blink_param1_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&blink_param_1_flds_we),
    .q_o(blink_param_1_qe)
  );
  // Create REGWEN-gated WE signal
  logic _blink_param_1_gated_we;
  assign _blink_param_1_gated_we = _blink_param_1_we & _blink_param_1_regwen;
  //   F[x_1]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_blink_param_1_x_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_blink_param_1_gated_we),
    .wd     (_blink_param_1_wdata[15:0]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (blink_param_1_flds_we[0]),
    .q      (reg2hw.blink_param[1].x.q),
    .ds     (),

    // to register interface (read)
    .qs     (_blink_param_1_x_1_qs_int)
  );
  assign reg2hw.blink_param[1].x.qe = blink_param_1_qe;

  //   F[y_1]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_blink_param_1_y_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (_blink_param_1_gated_we),
    .wd     (_blink_param_1_wdata[31:16]),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (blink_param_1_flds_we[1]),
    .q      (reg2hw.blink_param[1].y.q),
    .ds     (),

    // to register interface (read)
    .qs     (_blink_param_1_y_1_qs_int)
  );
  assign reg2hw.blink_param[1].y.qe = blink_param_1_qe;



  logic [9:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == PWM_REGWEN_OFFSET);
    addr_hit[1] = (reg_addr == PWM_CFG_OFFSET);
    addr_hit[2] = (reg_addr == PWM_PWM_EN_OFFSET);
    addr_hit[3] = (reg_addr == PWM_INVERT_OFFSET);
    addr_hit[4] = (reg_addr == PWM_PWM_PARAM_0_OFFSET);
    addr_hit[5] = (reg_addr == PWM_PWM_PARAM_1_OFFSET);
    addr_hit[6] = (reg_addr == PWM_DUTY_CYCLE_0_OFFSET);
    addr_hit[7] = (reg_addr == PWM_DUTY_CYCLE_1_OFFSET);
    addr_hit[8] = (reg_addr == PWM_BLINK_PARAM_0_OFFSET);
    addr_hit[9] = (reg_addr == PWM_BLINK_PARAM_1_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(PWM_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(PWM_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(PWM_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(PWM_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(PWM_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(PWM_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(PWM_PERMIT[6] & ~reg_be))) |
               (addr_hit[7] & (|(PWM_PERMIT[7] & ~reg_be))) |
               (addr_hit[8] & (|(PWM_PERMIT[8] & ~reg_be))) |
               (addr_hit[9] & (|(PWM_PERMIT[9] & ~reg_be)))));
  end

  // Generate write-enables
  assign regwen_we = addr_hit[0] & reg_we & !reg_error;

  assign regwen_wd = reg_wdata[0];
  assign cfg_we = addr_hit[1] & reg_we & !reg_error;



  assign pwm_en_we = addr_hit[2] & reg_we & !reg_error;


  assign invert_we = addr_hit[3] & reg_we & !reg_error;


  assign pwm_param_0_we = addr_hit[4] & reg_we & !reg_error;



  assign pwm_param_1_we = addr_hit[5] & reg_we & !reg_error;



  assign duty_cycle_0_we = addr_hit[6] & reg_we & !reg_error;


  assign duty_cycle_1_we = addr_hit[7] & reg_we & !reg_error;


  assign blink_param_0_we = addr_hit[8] & reg_we & !reg_error;


  assign blink_param_1_we = addr_hit[9] & reg_we & !reg_error;



  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = regwen_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next = DW'(cfg_qs);
      end
      addr_hit[2]: begin
        reg_rdata_next = DW'(pwm_en_qs);
      end
      addr_hit[3]: begin
        reg_rdata_next = DW'(invert_qs);
      end
      addr_hit[4]: begin
        reg_rdata_next = DW'(pwm_param_0_qs);
      end
      addr_hit[5]: begin
        reg_rdata_next = DW'(pwm_param_1_qs);
      end
      addr_hit[6]: begin
        reg_rdata_next = DW'(duty_cycle_0_qs);
      end
      addr_hit[7]: begin
        reg_rdata_next = DW'(duty_cycle_1_qs);
      end
      addr_hit[8]: begin
        reg_rdata_next = DW'(blink_param_0_qs);
      end
      addr_hit[9]: begin
        reg_rdata_next = DW'(blink_param_1_qs);
      end
      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  logic reg_busy_sel;
  assign reg_busy = reg_busy_sel | shadow_busy;
  always_comb begin
    reg_busy_sel = '0;
    unique case (1'b1)
      addr_hit[1]: begin
        reg_busy_sel = cfg_busy;
      end
      addr_hit[2]: begin
        reg_busy_sel = pwm_en_busy;
      end
      addr_hit[3]: begin
        reg_busy_sel = invert_busy;
      end
      addr_hit[4]: begin
        reg_busy_sel = pwm_param_0_busy;
      end
      addr_hit[5]: begin
        reg_busy_sel = pwm_param_1_busy;
      end
      addr_hit[6]: begin
        reg_busy_sel = duty_cycle_0_busy;
      end
      addr_hit[7]: begin
        reg_busy_sel = duty_cycle_1_busy;
      end
      addr_hit[8]: begin
        reg_busy_sel = blink_param_0_busy;
      end
      addr_hit[9]: begin
        reg_busy_sel = blink_param_1_busy;
      end
      default: begin
        reg_busy_sel  = '0;
      end
    endcase
  end


  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule


