// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "prim_assert.sv"

module spi_host_reg_top
  import spi_host_reg_pkg::* ;
(
  input logic clk_i,
  input logic rst_ni,
  // From TLUL
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output spi_host_reg_pkg::spi_host_reg2hw_t reg2hw, // Write
  input  spi_host_reg_pkg::spi_host_hw2reg_t hw2reg, // Read

  // Devmode
  input logic devmode_i // If 1, explicit error return for unmapped register access
);

  localparam int AW = 4;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(0),
    .EnableDataIntgGen(0)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;


  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_we;
  logic ctrl_en_qs;
  logic ctrl_en_wd;
  logic ctrl_txrst_qs;
  logic ctrl_txrst_wd;
  logic ctrl_rxrst_qs;
  logic ctrl_rxrst_wd;
  logic status_re;
  logic status_txfull_qs;
  logic status_txempty_qs;
  logic status_rxfull_qs;
  logic status_rxempty_qs;
  logic rdata_re;
  logic [7:0] rdata_qs;
  logic wdata_we;
  logic [7:0] wdata_wd;

  // Register instances
  // R[ctrl]: V(False)
  //   F[en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_en (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.en.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_en_qs)
  );

  //   F[txrst]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_txrst (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_txrst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.txrst.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_txrst_qs)
  );

  //   F[rxrst]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_rxrst (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_rxrst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.rxrst.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_rxrst_qs)
  );


  // R[status]: V(True)
  //   F[txfull]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_txfull (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.txfull.d),
    .qre    (reg2hw.status.txfull.re),
    .qe     (),
    .q      (reg2hw.status.txfull.q),
    .ds     (),
    .qs     (status_txfull_qs)
  );

  //   F[txempty]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_txempty (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.txempty.d),
    .qre    (reg2hw.status.txempty.re),
    .qe     (),
    .q      (reg2hw.status.txempty.q),
    .ds     (),
    .qs     (status_txempty_qs)
  );

  //   F[rxfull]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_rxfull (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rxfull.d),
    .qre    (reg2hw.status.rxfull.re),
    .qe     (),
    .q      (reg2hw.status.rxfull.q),
    .ds     (),
    .qs     (status_rxfull_qs)
  );

  //   F[rxempty]: 3:3
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_rxempty (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rxempty.d),
    .qre    (reg2hw.status.rxempty.re),
    .qe     (),
    .q      (reg2hw.status.rxempty.q),
    .ds     (),
    .qs     (status_rxempty_qs)
  );


  // R[rdata]: V(True)
  prim_subreg_ext #(
    .DW    (8)
  ) u_rdata (
    .re     (rdata_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.rdata.d),
    .qre    (reg2hw.rdata.re),
    .qe     (),
    .q      (reg2hw.rdata.q),
    .ds     (),
    .qs     (rdata_qs)
  );


  // R[wdata]: V(False)
  logic wdata_qe;
  logic [0:0] wdata_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_wdata0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&wdata_flds_we),
    .q_o(wdata_qe)
  );
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_wdata (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (wdata_we),
    .wd     (wdata_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (wdata_flds_we[0]),
    .q      (reg2hw.wdata.q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.wdata.qe = wdata_qe;



  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == SPI_HOST_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == SPI_HOST_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == SPI_HOST_RDATA_OFFSET);
    addr_hit[3] = (reg_addr == SPI_HOST_WDATA_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(SPI_HOST_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(SPI_HOST_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(SPI_HOST_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(SPI_HOST_PERMIT[3] & ~reg_be)))));
  end

  // Generate write-enables
  assign ctrl_we = addr_hit[0] & reg_we & !reg_error;

  assign ctrl_en_wd = reg_wdata[0];

  assign ctrl_txrst_wd = reg_wdata[1];

  assign ctrl_rxrst_wd = reg_wdata[2];
  assign status_re = addr_hit[1] & reg_re & !reg_error;
  assign rdata_re = addr_hit[2] & reg_re & !reg_error;
  assign wdata_we = addr_hit[3] & reg_we & !reg_error;

  assign wdata_wd = reg_wdata[7:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_en_qs;
        reg_rdata_next[1] = ctrl_txrst_qs;
        reg_rdata_next[2] = ctrl_rxrst_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_txfull_qs;
        reg_rdata_next[1] = status_txempty_qs;
        reg_rdata_next[2] = status_rxfull_qs;
        reg_rdata_next[3] = status_rxempty_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = rdata_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[7:0] = '0;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule


