name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25b
        with:
          pdk: sky130

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25b
        with:
          pdk: sky130

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Install Verilator (source build)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y git make g++ autoconf flex bison libfl2 libfl-dev zlib1g-dev help2man ccache
          tmpdir="$(mktemp -d)"
          git clone --depth=1 https://github.com/verilator/verilator.git "$tmpdir/verilator"
          pushd "$tmpdir/verilator"
          autoconf
          ./configure --prefix="$HOME/.local"
          make -j"$(nproc)"
          make install
          popd
          rm -rf "$tmpdir"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          which verilator
          verilator --version
      
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky25b
        with:
          pdk: sky130

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky25b
        with:
          pdk: sky130
